Restore Python 3.8 compatibility.
